### ISSUE TITLE
Support for changing Stills

### ISSUE THREAD

**Issue by uckligatorisch** [bitfocus/companion-module-mvr-helios#5]
Have the ability to show/hide a chosen still-image.

This can be done with the `POST /api/v1/media/:id/show` and the `POST /api/v1/media/hide` commands.

For now, it can only be done with the companion-generic-http-module.

**Comment by JellevanAbbema** [comment]
Hey, thanks for the issue. I've been a bit too busy, but I'll try to have a look at it next week. Definitly something that should be implemented.

**Comment by JellevanAbbema** [comment]
Just implemented a `show still` (with dropdown of available still images) and `hide still` action, will be included in the next release/beta
